# Generated by Django 5.2.10 on 2026-03-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True),
        ),
    ]
