# Generated by Django 5.2.10 on 2026-03-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('invoice', '0003_invoice_etims_synced_at_invoice_tax_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tax_invoice_number', models.CharField(blank=True, default='', max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_submissions', to='business.business')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_submissions', to='invoice.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tax_taxsubm_status_f26864_idx'), models.Index(fields=['tax_invoice_number'], name='tax_taxsubm_tax_inv_dd9691_idx')],
            },
        ),
    ]
