# Generated by Django 5.2.10 on 2026-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('invoice', '0003_invoice_etims_synced_at_invoice_tax_invoice_number'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('manual_invoice', 'Manual Invoice'), ('auto_paid', 'Auto Paid Notification')], default='manual_invoice', max_length=30),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['message_type'], name='messaging_w_message_9f62d0_idx'),
        ),
    ]
