# Generated by Django 5.2.10 on 2026-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_shape',
            field=models.CharField(choices=[('rect', 'Rect'), ('circle', 'Circle')], default='rect', max_length=12),
        ),
    ]
