# Generated by Django 5.2.10 on 2026-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_default_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='default_invoice_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('letterhead', 'Letterhead')], default='classic', max_length=20),
        ),
    ]
