# Generated by Django 5.2.10 on 2026-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='etims_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_invoice_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
