# Generated by Django 5.2.10 on 2026-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('letterhead', 'Letterhead')], default='', help_text='Blank inherits the business default template.', max_length=20),
        ),
    ]
